# Definir la versión del lenguaje que se está usando 
version: '3.8'

# Aquí se declaran todas las máquinas que se van a encender
services:
  # Máquina 1: Base de datos PostgreSQL
  PostgreSQL:
    image: postgres:15 
    container_name: db_TC1 # El nombre que tendrá el contenedor
    environment:
      # Se configura las credenciales por defecto de la base de datos
      POSTGRES_USER: UserTC1
      POSTGRES_PASSWORD: BaseDeDatosTC1
      POSTGRES_DB: TC_1 # El nombre de la base de datos que se va a crear automáticamente
    ports:
      - "5432:5432" # Abre el puerto para conectarse a la base de datos desde la compu
    volumes:
      # Guarda los datos en el disco duro para que 
      # si se apaga Docker, no se borren los restaurantes que guardados.
      - postgres_data:/var/lib/postgresql/data

  # Máquina 2: Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: auth_keycloak
    environment:
      # Usuario y contraseña para entrar a administrar Keycloak
      KEYCLOAK_ADMIN: UserTC1
      KEYCLOAK_ADMIN_PASSWORD: KeycloakTC1
    command: start-dev # Encender Keycloak en modo desarrollo
    ports:
      - "8080:8080" # Abrir Keycloak en el puerto 8080 del navegador
    depends_on:
      - PostgreSQL # Keycloak se enciende hasta que la base de datos esté lista"

  # Máquina 3: API
  api:
    build: ./api # Docker se va a la carpeta api y construye lo que se programó
    container_name: api_TC1
    ports:
      - "8000:8000"
    volumes:
      # Esto hace que si se guarda un cambio en el código Python, 
      # se actualice en vivo sin tener que reiniciar Docker.
      - ./api:/app
    environment:
      # Pasar a Python la dirección exacta, el usuario y la contraseña 
      # para que sepa cómo conectarse a la base de datos de PostgreSQL.
      - DATABASE_URL=postgresql://UserTC1:BaseDeDatosTC1@PostgreSQL:5432/TC_1
    depends_on:
      - PostgreSQL
      - keycloak

# Se declara el "disco duro" virtual que se usa arriba para la base de datos
volumes:
  postgres_data: