version: '3.8'

services:
  # Base de datos PostgreSQL
  PostgreSQL:
    image: postgres:15 
    container_name: db_TC1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      # Guarda los datos en el disco duro para que 
      # si se apaga Docker, no se borren los restaurantes que guardados.
      - postgres_data:/var/lib/postgresql/data

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: auth_keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev # Encender Keycloak en modo desarrollo
    ports:
      - "8080:8080"
    depends_on:
      - PostgreSQL

  # API
  api:
    build: ./api # Docker se va a la carpeta api y construye lo que se programó
    container_name: api_TC1
    ports:
      - "8000:8000"
    volumes:
      # Esto hace que si se guarda un cambio en el código Python, 
      # se actualice en vivo sin tener que reiniciar Docker.
      - ./api:/app
    env_file:
      - .env
    depends_on:
      - PostgreSQL
      - keycloak

# Se declara el "disco duro" virtual que se usa arriba para la base de datos
volumes:
  postgres_data: